### ISSUE TITLE
Max retries excedeed

### ISSUE THREAD

**Issue by otello86** [pcourbin/ecodevices_rt2#106]
Bonjour,
depuis la mise à jour de mon RT2 (je ne sais pas s'il y a un lien de cause à effet direct), j'ai fréquemment ces erreurs qui remontent dans les logs HA :

Logger: custom_components.ecodevices_rt2
Source: helpers/update_coordinator.py:151
Integration: GCE Ecodevices RT2 ([documentation](https://github.com/pcourbin/ecodevices_rt2), [issues](https://github.com/pcourbin/ecodevices_rt2/issues))
First occurred: 16:55:31 (4 occurrences)
Last logged: 17:13:11

Error requesting ecodevices_rt2 data: HTTPConnectionPool(host='192.168.31.3', port=80): Max retries exceeded with url: /api/xdevices.json?key=XXXXXX&Get=P (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effe2664a00>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
Error requesting ecodevices_rt2 data: HTTPConnectionPool(host='192.168.31.3', port=80): Max retries exceeded with url: /api/xdevices.json?key=XXXXXX&Get=D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effdff7d480>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
Error requesting ecodevices_rt2 data: HTTPConnectionPool(host='192.168.31.3', port=80): Max retries exceeded with url: /api/xdevices.json?key=XXXXXX&Get=D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f000126add0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
Error requesting ecodevices_rt2 data: HTTPConnectionPool(host='192.168.31.3', port=80): Max retries exceeded with url: /api/xdevices.json?key=XXXXXX&Price=all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effe185ca60>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

Ma configuration est la suivante : 
```
ecodevices_rt2:
 - name: EcoRT2
   host: "192.168.31.3"
   port: 80 # Optional, default: 80
   api_key: XXXXXX
   update_after_switch: 0   # Optional, default: 0 (seconds)
   scan_interval: 5
   devices:
     - name: Elect_instant
       type: "api"
       component: "sensor"
       api_get: "Get"
       api_get_value: "P"
       api_get_entry: "INSTANT_POSTE1"
#       type: "post"
#       id: 1
       device_class: "energy"
       unit_of_measurement: "Wh"
       state_class: "measurement"
       icon: "mdi:flash"
     - name: Elect_jour
       type: "post"
       id: 1
       device_class: "energy"
       unit_of_measurement: "Wh"
       state_class: "measurement"
       icon: "mdi:flash"
     - name: Injec_jour
       type: "api"
       component: "sensor"
       api_get: "DIndex"
       api_get_value: "S"
       api_get_entry: "P1_SSP1"
#       type: "post"
#       id: 1
#       subpost: 2
       device_class: "energy"
       unit_of_measurement: "kWh"
       state_class: "total_increasing"
       icon: "mdi:flash"
     - name: Eau_jour
       type: "post"
       id: 2
       unit_of_measurement: "L"
       state_class: "total_increasing"
       icon: "mdi:water"
     - name: Relais_EcoD
       type: "relay"
       id: 1
```
