### ISSUE TITLE
erreur d'index et de puissance instannée

### ISSUE THREAD

**Issue by cocoffr** [pcourbin/ecodevices_rt2#182]
## Configuration

```yaml
- name: EcoRT2_abris
  host: "192.168.1.65"
  port: 80 # Optional, default: 80
  api_key: 80 #!secret rt2_api_key
  update_after_switch: 0.1 # Optional, default: 0 (seconds)
  scan_interval: 60
  devices:
    #### Post and Sub-Post Example
    ###pompe piscine
    - name: pompe piscine
      type: "post"
      id: 6
      subpost: 0
  ###arrosage et prise
    - name: arrosage et prise abris
      type: "post"
      id: 6
      subpost: 1
    ###pompe a chaleur piscine
    - name: pompe a chaleur piscine
      type: "post"
      id: 6
      subpost: 2
  ### total prod abris
    - name: Total prod abris
      type: "post"
      id: 7
    ### panneaux 1 et 2
    - name: panneaux 1 et 2
      type: "post"
      id: 7
      subpost: 0
    ### panneaux 3 et 4
    - name: panneaux 3 et 4
      type: "post"
      id: 7
      subpost: 1
    ### panneau 5
    - name: panneau 5
      type: "post"
      id: 7
      subpost: 2
    ### panneau 6
    - name: panneau 6
      type: "post"
      id: 8
      subpost: 0
    #### Relay Example
    - name: Relay 1 RT2 Abris
      type: "relay" # Using default component `sensor`
      id: 1
    - name: Relais 2 RT2 Abris
      type: "relay"
      id: 2
- name: EcoRT2_maison
  host: "192.168.1.66"
  port: 80 # Optional, default: 80
  api_key: 80 #!secret rt2_api_key
  update_after_switch: 0.1 # Optional, default: 0 (seconds)
  scan_interval: 60
  devices:
    ### arrivée generale consommation via Linky
    - name: arrivee Linky
      type: "post"
      id: 1
      subpost: 0
    ### chauffage et ballon eau chaude
    ### Unité extérieur
    - name: PAC Unite extérieur
      type: "post"
      id: 2
      subpost: 0
    ### PAC unité intérieure
    - name: PAC unite interieure
      type: "post"
      id: 2
      subpost: 0
    ### arrivée generale
    - name: Arrivee generale
      type: "post"
      id: 4
      subpost: 0
    ### reinjection vers edf
    - name: reinjection vers edf
      type: "post"
      id: 5
      subpost: 0
    ### Disj 1
    - name: Disj 1
      type: "post"
      id: 6
      subpost: 0
    ### Disj 2
    - name: Disj 2
      type: "post"
      id: 6
      subpost: 1
    ### Disj 3
    - name: Disj 3
      type: "post"
      id: 6
      subpost: 2
    ### Disj 4 - conso PAC
    - name: Conso PAC
      type: "post"
      id: 2
    ### Clim parent et salon
    - name: Clim parent et salon
      type: "post"
      id: 7
      subpost: 0
    ### Clim enfants
    - name: Clim enfants
      type: "post"
      id: 7
      subpost: 1
    ### prod 3kWc
    - name: Panneaux 3kWc
      type: "post"
      id: 8
    #### Relay Example
    - name: Relay 1 RT2 maison
      type: "relay" # Using default component `sensor`
      id: 1
    - name: Relais 2 RT2 maison
      type: "relay"
      id: 2
```

## Describe the bug

les valeurs remontées dans HA ne sont pas cohérentes de ce qu'envoie l'écodevice. Tout d'abord sur les puissances instantanée, j'ai une sonde sur une pompe de piscine, elle tourne 30 min le matin. sous Ha je vois cette consommation, mais Ha remonte aussi des consos dans la journée alors que le pompe n'est pas en route. J'ai ce phénomène aussi sur la prod de mes panneaux solaires.
De même sur les énergies, les sensors d'index renvoie plusieurs fois par jours des mauvaise valeur (ex 1600kWh alors que l'index se situe autour des 200 kWh)
J'ai 2 Ecodevice, peut être que l'addon se mélange les pinceaux ?
En écrivant cet issue je viens de voir qu'ils 'agit bien de ca ! A certain moment, l'addon mélange mes 2 ecodevices : il écrit les valeurs du post 6/sous post1 de l'écodevice1 dans le sensor du post6/sous post1 de l'écodevice2.
Nota : j'utilise domoticz en parallèle : les données remontent sans erreur ca ne semble donc pas venir l'ecodevice mais plutôt de HA.
## Debug log

```text

Add your logs here.

```
