### ISSUE TITLE
remontée dans home assistant de la téléinfo

### ISSUE THREAD

**Issue by xavax59** [pcourbin/ecodevices_rt2#231]
Bonjour,
Je voudrais remonter les infos de la téléinfo de mon RT2 dans home assistant
Mon linky est en mode standard, est ce possible de faire ? 

<img width="1018" alt="image" src="https://github.com/pcourbin/ecodevices_rt2/assets/54884656/7076223e-7ef7-49cc-b77f-3fdf8a3f9e93">
je voudrais l'info LTARF par exemple
merci

**Comment by Loic691** [comment]
Salut
C'est quoi ces infos ? Elles semblent pas standard par rapport aux téléinfos classiques. Pourtant tu est en mode historique.
Tu as quoi comme abonnement ?
De mon coté j'ai pas de souci sur de l'abonnement HC/HP et TEMPO.

Sinon si ils te manquent des infos sur cette intégration tu peux tapper dans l'API du RT2 directement avec une commande REST dans HA. C'est ce que j'ai fait pour tout un tas de choses !

**Comment by xavax59** [comment]
Salut, mon linky est en mode standard. Si l’intégration n’est pas suivie je vais tester la méthode REST. Merci

**Comment by Loic691** [comment]
Ah oui ok, oui le mien est en historique. On a plus d'info je trouve mais bon.
Oui pour le plugin si il l'integration n'est pas mise à jour c'est pas si grave avec les API.
Mais pas c'est quand même tout de suite plus simple ;-)

**Comment by Loic691** [comment]
L'integration est bien toujours suivie même si les MAJ ne sont pas courante.
Pour moi l'integration fonctionne bien et la teleinfo remonte bien.
Il faut déjà voir si dans l'interface du rt2 tu as tout ce que tu veux

**Comment by pcourbin** [comment]
Bonsoir @xavax59 et @Loic691,

Merci beaucoup @Loic691 pour les réponses et l'accompagnement sur les différents sujets !
Désolé @xavax59, les mises à jours ne sont pas très régulières... 

Avez-vous pu bien trouver une solution grâce à @Loic691 ?
C'est bien tard, mais au cas où, même si ça n'est pas parfait, il toujours possible de faire appel à l'API effectivement, et notamment directement de l'intégration avec notamment le code suivant : 

```
      - name: Elec LTARF (from API)
        type: "api"
        api_get: "Get"
        api_get_value: "TI"
        api_get_entry: "LTARF"
 ```

Ça n'est pas parfait car c'est un texte qui est renvoyé, mais on peut bien ensuite jouer avec la valeur pour faire des tests au besoin, je l'avais fait à l'époque quand j'étais encore en HP/HC.
En espérant que les dernières mises à jours pourront être utiles.

**Comment by Loic691** [comment]
Effectivement @xavax59 
Dans la configuration YAML de l'integration RT2 tu peux remonter les étiquettes que tu souhaites
Un exemple chez moi pour le PTEC
```
- name: rt2_teleinfo_ptec
        type: "api"
        component: "sensor"
        api_get: "Get" 
        api_get_value: "TI" 
        api_get_entry: "PTEC" 
        icon: "mdi:flash"
```

A travers l'integration, j'arrive à obtenir toute ma téléinfo, les postes et sous postes du RT2, les commandes R/W des switchs, lire les compteurs, ....

Les seules choses que je n'arrive pas à obtenir sont les infos détaillées de chaque torre qui permettent d'obtenir ça.
Obligé de passer en API REST hors intégration
```
rest:
  - scan_interval: 10 # secondes
    resource: !secret rt2_url_torre
    authentication: basic
    username: !secret rt2_username
    password: !secret rt2_password
    sensor:

# Torre 4
      - name: "rt2_t4_puissance_pac_pisicne"
        unique_id: "rt2_t4_puissance_pac_pisicne"
        value_template: "{{ value_json.realpower53 }}"
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
      - name: "RT2 T4 Intensité PAC Pisicne"
        value_template: "{{ value_json.intensity53 }}"
        device_class: current
        state_class: measurement
        unit_of_measurement: "A"
      - name: "RT2 T4 Puissance apparente PAC Pisicne"
        value_template: "{{ value_json.apppower53 }}"
        device_class: "apparent_power"
        state_class: measurement
        unit_of_measurement: "VA"
      - name: "RT2 T4 Bruit PAC Pisicne"
        value_template: "{{ value_json.noise53 }}"
        device_class: signal_strength
        state_class: measurement
        unit_of_measurement: "dB"
      - name: "RT2 T4 Calibre PAC Pisicne"
        value_template: "{{ value_json.ampere53 }}"
        device_class: current
        unit_of_measurement: "A"
      - name: "rt2_t4_cos_phi_pac_pisicne"
        unique_id: "rt2_t4_cos_phi_pac_pisicne"
        value_template: " {% set cosphi = value_json.fp53 %}
          {{ (cosphi | float / 100 ) | round(2) if is_number(cosphi) else 1 }}"
        device_class: power_factor
        state_class: measurement 
# Torre 5
...
```
