### ISSUE TITLE
Device data no retrieve

### ISSUE THREAD

**Issue by otello86** [pcourbin/ecodevices_rt2#56]
I have a lot of bug since configuration of the relay of the RT2

## Version of the custom_component

Version of add-on : 2.2.3
Version HA : 2022.2.9

## Configuration

```
ecodevices_rt2:
 - name: EcoRT2
   host: "192.168.31.3"
   port: 80 # Optional, default: 80
   api_key: ########
   update_after_switch: 0   # Optional, default: 0 (seconds)
   scan_interval: 3
   devices:
     - name: Relais_EcoD
       type: "api"
       component: "switch"
       api_get: "Get"
       api_get_value: "R"
       api_get_entry: "R1"
       api_on_get: "SetR"
       api_on_get_value: "1"
       api_off_get: "ClearR"
       api_off_get_value: "1"
```

## Debug log
```
Logger: custom_components.ecodevices_rt2.switches.switch_ecodevicesrt2
Source: custom_components/ecodevices_rt2/switches/switch_ecodevicesrt2.py:32
Integration: GCE Ecodevices RT2 ([documentation](https://github.com/pcourbin/ecodevices_rt2), [issues](https://github.com/pcourbin/ecodevices_rt2/issues))
First occurred: 28 février 2022, 15:44:55 (2 occurrences)
Last logged: 07:45:23

Device data no retrieve Relais_EcoD: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()` at custom_components/ecodevices_rt2/switches/switch_api.py, line 44: self.ecort2.get( (False)
```

**Comment by pcourbin** [comment]
Bonjour @otello86, 

Merci pour ce retour détaillé.
J'ai essayé de reproduire l'erreur, mais rien n'apparaissait... jusqu'à ce que je fasse la mise à jour HA en 2022.2.9.
Je vois d'où vient le problème mais je ne vais pas pouvoir le corriger tout de suite. 

Deux questions/propositions pour avancer tout de même :

1. Normalement, vous devriez avoir quelques erreurs au démarrage, mais cela devrait s'arrêter ensuite, non ?
2. Pouvez-vous tester de remplacer votre configuration par celle-ci et me dire si vous avez les mêmes problèmes ?

```yaml
    - name: Relais_EcoD
      type: "relay"
      id: 1
```

Cela fait exactement la même configuration que ce que vous avez indiqué, mais en utilisant les objets "Relay" définis dans le module pour faciliter l'ajout de devices et qui font les appels de façon un peu plus propre... il faut que je corrige les modules "API" il me semble.
